version: '3.8'

services:
  jenkins:
    image: tinybrick/jenkins
    build:
      context: .
    container_name: jenkins-master
    hostname: jenkins-master
    restart: always
    ports:
      - 8084:8080    #pulish to outer port 8084
    expose:
      - "50000"      #for JNPL agent to connect from intranet
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock:ro
    healthcheck:
      test: 'curl --conect-timeout 5 --silent http://127.0.0.1:8080 || exit 1'
      interval: 5s
      timeout: 3s
      retries: 3
    networks:
      - frontend-network
      - backbone-network

volumes:
  jenkins-data:

networks:
  frontend-network:
    external:
      name: frontend-network
  backbone-network:
    external:
      name: backbone-network

